### DISCUSSION TITLE
Is it possible to nest (and loop over) data in frontmatter?

### DISCUSSION THREAD

**Discussion by nathangross** [tighten/jigsaw#595] [Q&A] [answered]
As far as I can tell, nesting collections is not currently supported (#579) but I was curious if you could achieve something similar with nested frontmatter data? I saw this [post](https://github.com/11ty/eleventy/issues/534) regarding a different SSG. 

I was hoping something like this would work but it doesn't' seem to. 

```
---
title: 'The main title'
subcollection:
- title: 'Voluptate minim Lorem nulla esse eiusmod dolore amet ad nulla'
  text: 'Ipsum in aliquip veniam occaecat Lorem non fugiat ipsum consequat deserunt.'
- title: 'Reprehenderit sunt officia voluptate anim voluptate non'
  text: 'Dolor veniam ex do deserunt esse ex cupidatat labore est reprehenderit elit culpa.'
  ---
  
@foreach ($page->subcollection as $item )
    {{ $item->title }}
@endforeach
```

Are there any good ways, currently, to nest like this?

**Comment by bakerkretzmar** [comment, marked as answer]
That actually does work, but each nested item will be an array, not an object:

```diff
-     {{ $item->title }}
+     {{ $item['title'] }}
```

Also, this doesn't seem to actually matter, but I think technically your nested YAML items should be indented further:

```
subcollection:
  - title: 'Voluptate minim Lorem nulla esse eiusmod dolore amet ad nulla'
    text: 'Ipsum in aliquip veniam occaecat Lorem non fugiat ipsum consequat deserunt.'
  - title: 'Reprehenderit sunt officia voluptate anim voluptate non'
    text: 'Dolor veniam ex do deserunt esse ex cupidatat labore est reprehenderit elit culpa.'
```
