### DISCUSSION TITLE
YAML multiline segments

### DISCUSSION THREAD

**Discussion by ju5t** [tighten/jigsaw#606] [Q&A]
I'd like to document our API in Jigsaw but as a new Jigsaw user, I am unsure if I'm doing things right.

One of the things I want to do is custom code blocks. I would like to document this in our markdown files. As other API docs, I'd like the examples to be on the right of the page, so they can't be inline in the markdown itself.

So here's my current approach:

```yaml
body:
  - foo: Username
  - bar: Password
uri: authenticate
code: |
    <?php
    echo $foo;
```

This works. But when I'm using inside `<pre>` or Torchlight, it will indent the first line. I don't want that. I am guessing that we will normally build the code example based on the body and possibly other fields, but there will be exceptions.

What would be the best approach here?

**Comment by bakerkretzmar** [comment]
It looks to me like that YAML actually is indented a bit too much, does it work like this?

```yaml
body:
  - foo: Username
  - bar: Password
uri: authenticate
code: |
  <?php
  echo $foo;
```

(Not this)

```yaml
code: |
    <?php
    echo $foo;
```
